version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/app
      - ./scripts:/app/scripts
    ports:
      - 8000:8000
    environment:
      - DATABASE=postgres
      - PG_USER=openweather
      - PG_PASSWORD=openweather
      - PG_DB=openweather
      - PG_HOST=db
      - SECRET_KEY=django-insecure-secret-key
      - MIGRATE_ON_STARTUP=True
    depends_on:
      - db
  db:
    image: postgres:15.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=openweather
      - POSTGRES_PASSWORD=openweather
      - POSTGRES_DB=openweather

volumes:
  postgres_data:
